mod biology_sim;
//mod water_sim;

use bevy::{
    ecs::{
        resource::Resource,
        system::{Res, ResMut},
    },
    math::IVec2,
};
use flume::{Receiver, Sender};
use rand::RngExt;
use rayon::iter::{IndexedParallelIterator, IntoParallelRefMutIterator, ParallelIterator};
//pub use water_sim::WaterSimulationConfig;

use crate::prelude::{ActiveWorldGrid, MaterialId};

/// Events generated by the lock-free engine CA that affect the external ECS world.
pub enum GridEvent {
    SpawnParticle { pos: IVec2, material: MaterialId },
    ApplyDamage { pos: IVec2, amount: u32 },
    PlaySound { pos: IVec2, sound_id: u8 },
}

#[derive(Resource)]
pub struct SimulationEventQueue {
    pub tx: Sender<GridEvent>,
    pub rx: Receiver<GridEvent>,
}

impl Default for SimulationEventQueue {
    fn default() -> Self {
        let (tx, rx) = flume::unbounded();
        Self { tx, rx }
    }
}

pub fn simulate_world(
    mut grid_res: ResMut<ActiveWorldGrid>,
    event_queue: Res<SimulationEventQueue>,
) {
    let width = grid_res.width;
    let height = grid_res.height;

    // Prepare buffers
    grid_res.swap_buffers();
    let grid_mut = grid_res.into_inner();

    // Bind read-only historical buffer and the global MPSC sender
    let read_buffer = &grid_mut.back_buffer;
    let global_tx = event_queue.tx.clone();

    // Single Parallel Pass
    grid_mut
        .cells
        .par_iter_mut()
        .enumerate()
        .for_each_with(global_tx, |tx, (idx, cell)| {
            let mut rng = rand::rng();

            // Random Monte-Carlo selection
            if !rng.random_ratio(1, 10) {
                return;
            }

            let x = (idx as i32) % width;
            let y = (idx as i32) / width;
            let pos = bevy::math::IVec2::new(x, y);

            let old_cell = &read_buffer[idx];

            // Biology & Atmosphere
            biology_sim::step_biology(
                cell,
                old_cell,
                read_buffer,
                width,
                height,
                &mut rng,
                tx,
                pos,
            );

            // TODO: Water / Fluids (to be implemented)
            // water_sim::step_water(...)
        });

    grid_mut.cells_dirty = true;
}
