mod biology_sim;
pub mod liquid_sim;

use bevy::{
    ecs::{
        resource::Resource,
        system::{Res, ResMut},
    },
    math::IVec2,
};
use flume::{Receiver, Sender};
use rand::RngExt;
use rayon::iter::{IndexedParallelIterator, IntoParallelRefMutIterator, ParallelIterator};

use crate::prelude::{ActiveWorldGrid, MaterialId};

/// Events generated by the lock-free engine CA that affect the external ECS world.
pub enum GridEvent {
    SpawnParticle { pos: IVec2, material: MaterialId },
    ApplyDamage { pos: IVec2, amount: u32 },
    PlaySound { pos: IVec2, sound_id: u8 },
}

#[derive(Resource)]
pub struct SimulationEventQueue {
    pub tx: Sender<GridEvent>,
    pub rx: Receiver<GridEvent>,
}

impl Default for SimulationEventQueue {
    fn default() -> Self {
        let (tx, rx) = flume::unbounded();
        Self { tx, rx }
    }
}

pub fn simulate_world(
    mut grid_res: ResMut<ActiveWorldGrid>,
    event_queue: Res<SimulationEventQueue>,
) {
    let width = grid_res.width;
    let height = grid_res.height;

    // Prepare buffers
    grid_res.swap_buffers();
    let grid_mut = grid_res.into_inner();

    let tick = grid_mut.tick;
    let read_buffer = &grid_mut.back_buffer;
    let global_tx = event_queue.tx.clone();

    // Single Parallel Pass
    grid_mut
        .cells
        .par_iter_mut()
        .enumerate()
        .for_each_with(global_tx, |tx, (idx, cell)| {
            let mut rng = rand::rng();

            let x = (idx as i32) % width;
            let y = (idx as i32) / width;
            let pos = bevy::math::IVec2::new(x, y);

            let old_cell = &read_buffer[idx];

            // ---------------------------------------------------------
            // DETERMINISTIC PHYSICS (Mass Transfer)
            // ---------------------------------------------------------
            // Liquid CA MUST evaluate globally to maintain symmetric
            // lock-free consensus. Throttling is handled via modulo.
            if tick % 2 == 0 {
                liquid_sim::step_liquid(cell, old_cell, read_buffer, width, height, &mut rng, pos);
            }

            // ---------------------------------------------------------
            // SPARSE BIOLOGY (In-Place Mutation)
            // ---------------------------------------------------------
            // Random Monte-Carlo selection is safe here because biology
            // only mutates its own local state (e.g. aging).
            if rng.random_ratio(1, 10) {
                biology_sim::step_biology(
                    cell,
                    old_cell,
                    read_buffer,
                    width,
                    height,
                    &mut rng,
                    tx,
                    pos,
                );
            }
        });

    grid_mut.cells_dirty = true;
}
