use super::Chunk;
use super::math::{ChunkKey, ChunkView};
use crate::prelude::ToroidalGrid;

use lru::LruCache;
use rustc_hash::{FxBuildHasher, FxHashMap, FxHashSet};
use std::num::NonZeroUsize;

/// Engine-agnostic storage for the topological state of chunks.
#[derive(Debug)]
pub struct ChunkStore<T, M = ()> {
    pub active: FxHashMap<ChunkKey, Chunk<T, M>>,
    pub cached: LruCache<ChunkKey, Chunk<T, M>, FxBuildHasher>,
    pub pending: FxHashSet<ChunkKey>,
}

impl<T, M> ChunkStore<T, M> {
    pub fn new(cache_capacity: usize) -> Self {
        Self {
            active: FxHashMap::default(),
            cached: LruCache::with_hasher(
                NonZeroUsize::new(cache_capacity)
                    .expect("Cache capacity must be mathematically non-zero"),
                FxBuildHasher,
            ),
            pending: FxHashSet::default(),
        }
    }
}

/// Contains the deterministic I/O demands generated by a focus shift or resize.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WindowEvents<T, M> {
    pub loads_requested: Vec<ChunkKey>,
    pub unloads_emitted: Vec<(ChunkKey, Chunk<T, M>)>,
}

#[derive(Debug, Clone)]
pub struct ChunkManager {
    pub active_view: Option<ChunkView>,
    pub preload_view: Option<ChunkView>,
    pub active_radius_x: u32,
    pub active_radius_y: u32,
    pub preload_radius: u32,
    pub preload_trigger: u32,
    pub chunk_size: usize,
}

impl ChunkManager {
    pub fn new(
        active_rx: u32,
        active_ry: u32,
        preload_ext: u32,
        trigger: u32,
        chunk_size: usize,
    ) -> Self {
        Self {
            active_view: None,
            preload_view: None,
            active_radius_x: active_rx,
            active_radius_y: active_ry,
            preload_radius: preload_ext,
            preload_trigger: trigger,
            chunk_size,
        }
    }

    /// Translates a focal shift into strict grid alignments, cache demotions, and I/O buffer schedules.
    pub fn manage_window<T: Default + Clone, M: Default + Clone>(
        &mut self,
        center: ChunkKey,
        store: &mut ChunkStore<T, M>,
        grid: &mut ToroidalGrid<T>,
    ) -> WindowEvents<T, M> {
        let mut events = WindowEvents {
            loads_requested: Vec::new(),
            unloads_emitted: Vec::new(),
        };

        let new_active_view = ChunkView::from_rect_xy(
            center,
            self.active_radius_x as i32,
            self.active_radius_y as i32,
        );

        if self.active_view != Some(new_active_view) {
            if let Some(old_active) = self.active_view {
                for key in old_active.iter().filter(|k| !new_active_view.contains(k)) {
                    if let Some(mut chunk_data) = store.active.remove(&key) {
                        grid.extract_chunk_into(key, self.chunk_size, &mut chunk_data.cells);
                        if let Some((evicted_key, evicted_data)) =
                            store.cached.push(key, chunk_data)
                        {
                            events.unloads_emitted.push((evicted_key, evicted_data));
                        }
                    }
                }
            }

            grid.shift_window(new_active_view.min.to_ivec2() * (self.chunk_size as i32));

            let old_active_ref = self.active_view.as_ref();
            for key in new_active_view
                .iter()
                .filter(|k| old_active_ref.map_or(true, |old| !old.contains(k)))
            {
                if let Some(chunk_data) = store.cached.pop(&key) {
                    grid.load_chunk(key, self.chunk_size, &chunk_data.cells);
                    store.active.insert(key, chunk_data);
                } else if !store.active.contains_key(&key) && store.pending.insert(key) {
                    events.loads_requested.push(key);
                }
            }
            self.active_view = Some(new_active_view);
        }

        let mut requires_preload = false;
        if let Some(current_preload) = self.preload_view {
            let danger_view = ChunkView::from_rect_xy(
                center,
                (self.active_radius_x + self.preload_trigger) as i32,
                (self.active_radius_y + self.preload_trigger) as i32,
            );

            if !current_preload.contains(&danger_view.min)
                || !current_preload.contains(&danger_view.max)
            {
                requires_preload = true;
            }
        } else {
            requires_preload = true;
        }

        if requires_preload {
            let new_preload_view = ChunkView::from_rect_xy(
                center,
                (self.active_radius_x + self.preload_radius) as i32,
                (self.active_radius_y + self.preload_radius) as i32,
            );

            let old_preload_ref = self.preload_view.as_ref();
            for key in new_preload_view
                .iter()
                .filter(|k| old_preload_ref.map_or(true, |old| !old.contains(k)))
            {
                if !store.active.contains_key(&key)
                    && !store.cached.contains(&key)
                    && store.pending.insert(key)
                {
                    events.loads_requested.push(key);
                }
            }
            self.preload_view = Some(new_preload_view);
        }

        events
    }

    /// Safely halts the grid, extracts live data, contracts geometric bounds, and repopulates without loss.
    pub fn handle_resize<T: Default + Clone, M: Default + Clone>(
        &mut self,
        center: ChunkKey,
        new_radius_x: u32,
        new_radius_y: u32,
        store: &mut ChunkStore<T, M>,
        grid: &mut ToroidalGrid<T>,
    ) -> WindowEvents<T, M> {
        let mut events = WindowEvents {
            loads_requested: Vec::new(),
            unloads_emitted: Vec::new(),
        };

        let new_active_view =
            ChunkView::from_rect_xy(center, new_radius_x as i32, new_radius_y as i32);

        if let Some(old_active) = self.active_view {
            for key in old_active.iter() {
                if let Some(chunk_data) = store.active.get_mut(&key) {
                    grid.extract_chunk_into(key, self.chunk_size, &mut chunk_data.cells);
                }
            }

            for key in old_active.iter().filter(|k| !new_active_view.contains(k)) {
                if let Some(chunk_data) = store.active.remove(&key) {
                    if let Some((evicted_key, evicted_data)) = store.cached.push(key, chunk_data) {
                        events.unloads_emitted.push((evicted_key, evicted_data));
                    }
                }
            }
        }

        let span_chunks_x = (new_radius_x * 2 + 1) as i32;
        let span_chunks_y = (new_radius_y * 2 + 1) as i32;
        let new_width = span_chunks_x * (self.chunk_size as i32);
        let new_height = span_chunks_y * (self.chunk_size as i32);
        let new_origin = new_active_view.min.to_ivec2() * (self.chunk_size as i32);

        grid.resize_in_place(new_width, new_height, new_origin);

        for key in new_active_view.iter() {
            if let Some(chunk_data) = store.active.get(&key) {
                grid.load_chunk(key, self.chunk_size, &chunk_data.cells);
            } else if let Some(chunk_data) = store.cached.pop(&key) {
                grid.load_chunk(key, self.chunk_size, &chunk_data.cells);
                store.active.insert(key, chunk_data);
            } else if store.pending.insert(key) {
                events.loads_requested.push(key);
            }
        }

        self.active_radius_x = new_radius_x;
        self.active_radius_y = new_radius_y;
        self.active_view = Some(new_active_view);
        self.preload_view = None;

        events
    }

    /// Ingests data retrieved over asynchronous boundaries into the active grid or cache depending on view shifts.
    pub fn handle_chunk_loaded<T: Default + Clone, M: Default + Clone>(
        &mut self,
        key: ChunkKey,
        chunk_data: Chunk<T, M>,
        store: &mut ChunkStore<T, M>,
        grid: &mut ToroidalGrid<T>,
    ) -> Option<(ChunkKey, Chunk<T, M>)> {
        store.pending.remove(&key);

        let is_active = self.active_view.map_or(false, |v| v.contains(&key));

        if is_active {
            grid.load_chunk(key, self.chunk_size, &chunk_data.cells);
            store.active.insert(key, chunk_data);
            None
        } else {
            if let Some((evicted_key, evicted_data)) = store.cached.push(key, chunk_data) {
                Some((evicted_key, evicted_data))
            } else {
                None
            }
        }
    }
}
